name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.11.0'

    - name: Build Zig Project
      run: |
        zig build

    - name: Generate release tag
      id: generate_release_tag
      uses: amitsingh-007/next-release-tag@v5.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: 'v'
        tag_template: 'i'

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'v0'
        generateReleaseNotes: true
        makeLatest: true
