name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: '0.11.0'

    - name: Build Zig Project
      run: |
        zig build

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: 'v0'
        artifacts: 'web/**/*'
